services:
  # Users Service
  users:
    build: ./backend/users
    ports: ["8000:8000"]
    depends_on:
      - db-users
    environment:
      - DATABASE_URL=postgresql://admin:pass@db-users:5432/users_db

  # Posts Service
  posts:
    build: ./backend/posts
    ports: ["8001:8000"]
    depends_on:
      - db-posts
    environment:
      - DATABASE_URL=postgresql://admin:pass@db-posts:5432/posts_db

  # Базы данных
  db-users:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users_db

  db-posts:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: posts_db